channels:
- conda-forge
dependencies:
- python=3.10.10
- pip<=23.0.1
- pip:
  - mlflow==2.12.1
  - cloudpickle==2.0.0
  - numpy==1.24.3
  - packaging==23.0
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
